name: Tests
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  test:
    name: Testing CodeEdit
    runs-on: [self-hosted, macOS]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Testing App
        run: exec ./.github/scripts/test_app.sh arm
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: out
  token: $GITHUB_TOKEN
  target_branch: gh-pages
  keep_history: true
  on:
    branch: main
